version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t weatherapp .

      - run:
          name: Start Docker container
          command: docker run -d -p 9090:9090 weatherapp

      - run:
          name: Wait for the service to start
          command: |
            for i in `seq 1 10`; do
              curl http://127.0.0.1:9090 && break
              echo "Waiting for service to start..."
              sleep 3
            done

      - run:
          name: Run Tests
          command: python tests/reachability.py
