version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Ensure a compatible Docker version
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: docker build -t weatherapp .

      - run:
          name: Start Docker container
          command: docker run -d --name weatherapp_container weatherapp

      - run:
          name: Run Tests
          command: docker exec weatherapp_container python tests/reachability.py

      - run:
          name: Tag Docker image for GitLab Registry
          command: docker tag weatherapp registry.gitlab.com/or4153322/weatherapp:$CIRCLE_BUILD_NUM

      - run:
          name: Login to GitLab Registry
          command: |
            echo "$GITLAB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com

      - run:
          name: Push Docker image to GitLab Registry
          command: docker push registry.gitlab.com/or4153322/weatherapp:$CIRCLE_BUILD_NUM

      - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          success_message: "**${CIRCLE_USERNAME}** deployed api to prod."
          webhook: https://discord.com/api/webhooks/1244981576555827260/zrUbDLPpZLNoi7bYFxtBzFUqqD1dT8s_8oQ3vOpJToNaIWFVIKDiR4pfA50F-LErzKyW

workflows:
  your-workflow:
    jobs:
      - build
