version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - setup_remote_docker:

      - run:
          name: Build Docker image
          command: docker build -t weatherapp .

      - run:
          name: Start Docker container
          command: docker run -d --name weatherapp_container weatherapp

      - run:
          name: Wait for container to start
          command: docker logs -f weatherapp_container | grep "Application started" -m 1

      - run:
          name: Run Tests
          command: docker exec weatherapp_container python tests/reachability.py
