version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t weatherapp .
      - run:
          name: Run simple test
          command: |
            python tests/reachability.py

# # Workflow to orchestrate job execution
# workflows:
  # build_and_test:
    # jobs:
      # - build
      # - test:
          # requires:
            # - build  # Ensure 'test' job runs after 'build' finishes
