version: 2.1

orbs:
  discord: teka23/discord@0.0.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Ensure a compatible Docker version
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: docker build -t weatherapp .

      - run:
          name: Start Docker container
          command: docker run -d --name weatherapp_container weatherapp

      - run:
          name: Run Tests
          command: docker exec weatherapp_container python tests/reachability.py

      - discord/notify:
          color: '4383476'
          mentions: or.aharon
          message: This is a custom message notificatin
          webhook: https://discord.com/api/webhooks/1244981576555827260/zrUbDLPpZLNoi7bYFxtBzFUqqD1dT8s_8oQ3vOpJToNaIWFVIKDiR4pfA50F-LErzKyW

workflows:
  your-workflow:
    jobs:
      - build
