version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - setup_remote_docker:

      - run:
          name: Build Docker image
          command: docker build -t weatherapp .

      - run:
          name: Start Docker container
          command: docker run -d  --name weatherapp_container weatherapp

      - run:
          name: Run Tests
          command: |
            docker exec -it weatherapp_container python tests/reachability.py

