version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Ensure a compatible Docker version
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: docker build -t weatherapp .

      - run:
          name: Create Docker network
          command: docker network create weatherapp_network

      - run:
          name: Start Docker container
          command: docker run -d --network weatherapp_network --name weatherapp_container weatherapp

      - run:
          name: Wait for the service to start
          command: |
            WEATHERAPP_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' weatherapp_container)
            echo "Container IP: $WEATHERAPP_IP"
            for i in `seq 1 10`; do
              if curl -s http://$WEATHERAPP_IP:9090; then
                echo "Service is up!"
                break
              else
                echo "Waiting for service to start... attempt $i"
                sleep 3
              fi
            done
            if [ $i -eq 10 ]; then
              echo "Service did not start in time. Here are the container logs:"
              docker logs weatherapp_container
              exit 1
            fi

      - run:
          name: Check Docker container logs
          command: docker logs weatherapp_container

      - run:
          name: Run Tests
          command: |
            WEATHERAPP_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' weatherapp_container)
            export WEATHERAPP_IP
            python tests/reachability.py
