version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - setup_remote_docker:
      
      - run:
          name: Build Docker image
          command: docker build -t weatherapp .

      - run:
          name: Create Docker network
          command: docker network create weatherapp_network

      - run:
          name: Start Docker container
          command: docker run -d --network weatherapp_network --name weatherapp_container weatherapp

      - run:
          name: Check Docker container logs
          command: docker logs weatherapp_container

      - run:
          name: Run Tests
          command: |
            WEATHERAPP_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' weatherapp_container)
            export WEATHERAPP_IP
            python tests/reachability.py
