name: CI for weatherapp
on:
  push:
    branches: [ "main" ]

jobs:
  integration:
    name: security scanning
    runs-on: ubuntu-latest
    steps:
      - name: SAST scan with gitleaks
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
