name: CI for weatherapp
on:
  push:
    branches: [ "main" ]

jobs:
  scan:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check dependencies
        uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: requirements.txt

      - name: Build and scan image
        uses: dentsusoken/build-and-scan-image@main
        with:
          tag: "oraharon/weatherapp_github_actions:${{github.run_number}}"
          path: "."
