name: CI for weatherapp
on:
  push:
    branches: [ "main" ]

jobs:
  scan-git:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  scan-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check dependencies
        uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: requirements.txt

  scan-dockerfile-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and scan image
        uses: dentsusoken/build-and-scan-image@main
        with:
          tag: "oraharon/weatherapp_github_actions:${{github.run_number}}"
          path: "."
          hadolint-severity: info
          dockle-severity: WARN
          snyk-severity: low

      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.0.0
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key oraharon/weatherapp_github_actions:${{ github.run_number }}
      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
