name: CI for weatherapp
on:
  push:
    branches: [ "main" ]

jobs:
  scan-git:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  scan-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check dependencies
        uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: requirements.txt

  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master

  scan-dockerfile-and-build:
    needs: [scan-dependencies, scan-git, codacy-analysis-cli]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and scan image
        uses: dentsusoken/build-and-scan-image@main
        with:
          tag: "oraharon/weatherapp_github_actions:${{github.run_number}}"
          path: "."
          hadolint-severity: info
          dockle-severity: WARN
          snyk-severity: low

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp_github_actions:${{github.run_number}}

  sign-container:
    needs: scan-dockerfile-and-build
    name: Sign container with cosign
    runs-on: ubuntu-latest
    steps:

      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp_github_actions:${{github.run_number}}

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.5.0

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Sign the published Docker image to dockerhub
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp_github_actions:${{ github.run_number }} -y

  CD:
    needs: sign-container
    name: verify deployment
    runs-on: ubuntu-latest
    steps:

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.5.0

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}

      - name: Verify the published Docker image
        run: cosign verify --key cosign.key ${{ secrets.DOCKERHUB_USERNAME }}/weatherapp_github_actions:${{ github.run_number }}
